version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: karbon_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: karbon_payments
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  payment-orchestration:
    build:
      context: ./payment-orchestration-service
    container_name: payment_orchestration_service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: karbon_payments
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  mock-gateway:
    build:
      context: ./mock-payment-gateway
    container_name: mock_payment_gateway
    ports:
      - "3002:3002"
    depends_on:
      - payment-orchestration

  transaction-query:
    build:
      context: ./transaction-query-service
    container_name: transaction_query_service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: karbon_payments
    ports:
      - "3003:3003"
    depends_on:
      - postgres

volumes:
  pgdata:
