version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: karbon_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: karbon_payments
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  payment-orchestration:
    build:
      context: ./payment-orchestration-service
    container_name: payment_orchestration_service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: karbon_payments
    ports:
      - "3001:3001"
    depends_on:
      - postgres

volumes:
  pgdata:
